# Generated by Django 4.2.11 on 2024-04-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymenu', '0002_remove_menuitems_menu_menuitems_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='isroot',
            field=models.BooleanField(default=False, verbose_name='Корневой элемент'),
        ),
    ]
