# Generated by Django 4.2.11 on 2024-04-21 10:05

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mymenu', '0003_menuitems_isroot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='menu',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.fields.Empty, related_name='Items', to='mymenu.menu'),
            preserve_default=False,
        ),
    ]
