# Generated by Django 4.2.11 on 2024-04-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymenu', '0004_remove_menuitems_menu_menuitems_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='Items', to='mymenu.menu'),
        ),
    ]
