# Generated by Django 4.2.11 on 2024-04-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymenu', '0005_remove_menuitems_menu_menuitems_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='menu',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Items', to='mymenu.menu'),
            preserve_default=False,
        ),
    ]
